import type { Icon } from "@phosphor-icons/react";
import {
  AlignBottom,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignLeft,
  AlignRight,
  AlignTop,
  AppWindow,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowsIn,
  ArrowsOut,
  ArrowsOutCardinal,
  CaretDown,
  CaretLeft,
  CaretRight,
  Check,
  Circle,
  CircleHalf,
  Columns,
  Copy,
  Cursor,
  Door,
  DownloadSimple,
  Eye,
  EyeSlash,
  FlipHorizontal,
  FlipVertical,
  FloppyDisk,
  Folder,
  Gear,
  GridFour,
  Hand,
  LineSegment,
  Lock,
  LockOpen,
  Magnet,
  MagnifyingGlass,
  Minus,
  PaintBrush,
  PencilLine,
  PencilSimple,
  Plus,
  Polygon,
  Rectangle,
  RectangleDashed,
  Rows,
  Ruler,
  SlidersHorizontal,
  SquaresFour,
  Stack,
  Star,
  TextT,
  Trash,
  Triangle,
  UploadSimple,
  Wall,
  X,
} from "@phosphor-icons/react";

/**
 * Stable icon keys → Phosphor components. The Studio's own map; the Planner has
 * its own copy. Every icon in this app resolves through here — no inline SVG,
 * no direct Phosphor imports in components.
 */
export const PH_ICON_MAP = {
  cursor: Cursor,
  hand: Hand,
  rect: Rectangle,
  roundedRect: RectangleDashed,
  circle: Circle,
  ellipse: Circle,
  triangle: Triangle,
  star: Star,
  line: LineSegment,
  arrow: ArrowRight,
  arc: CircleHalf,
  polygon: Polygon,
  text: TextT,
  freehand: PencilLine,
  pen: PencilSimple,
  brush: PaintBrush,
  wall: Wall,
  door: Door,
  window: AppWindow,
  dimension: Ruler,
  undo: ArrowCounterClockwise,
  redo: ArrowClockwise,
  save: FloppyDisk,
  download: DownloadSimple,
  trash: Trash,
  copy: Copy,
  group: SquaresFour,
  eye: Eye,
  eyeOff: EyeSlash,
  lock: Lock,
  unlock: LockOpen,
  plus: Plus,
  minus: Minus,
  search: MagnifyingGlass,
  grid: GridFour,
  magnet: Magnet,
  layers: Stack,
  properties: SlidersHorizontal,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  x: X,
  check: Check,
  upload: UploadSimple,
  maximize: ArrowsOut,
  minimize: ArrowsIn,
  expand: ArrowsOutCardinal,
  folder: Folder,
  gear: Gear,
  caretLeft: CaretLeft,
  caretRight: CaretRight,
  caretDown: CaretDown,

  /** Align / distribute / flip bar. */
  alignLeft: AlignLeft,
  alignCenterX: AlignCenterVertical,
  alignRight: AlignRight,
  alignTop: AlignTop,
  alignCenterY: AlignCenterHorizontal,
  alignBottom: AlignBottom,
  distH: Columns,
  distV: Rows,
  flipH: FlipHorizontal,
  flipV: FlipVertical,
  rotate: ArrowClockwise,
} as const satisfies Record<string, Icon>;

export type PhIconName = keyof typeof PH_ICON_MAP;

export function resolvePhIcon(name: string): Icon {
  if (name in PH_ICON_MAP) return PH_ICON_MAP[name as PhIconName];
  return PH_ICON_MAP.cursor;
}
